stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t angular .

deploy:
  stage: deploy
  script:
    - docker run -p 88:88 angular
    - echo 'docker run successfully'
